// [WARNING] This file is generated by running `$ qore codegen` on your root project, please do not edit

/// <reference types="@feedloop/qore-client" />
import { QoreSchema } from "@feedloop/qore-client";

declare module "@feedloop/qore-client" {
  type MemberTableRow = {
    id: string;
    email: string;
    role: { id: string; displayField: string };
    password: string;
    messages1: { nodes: Messages1TableRow[] };
    channels: { nodes: ChannelsTableRow[] };
  };

  type ChannelTableRow = {
    id: string;
    name: string;
    messages: { nodes: MessagesTableRow[] };
    member1: { nodes: Member1TableRow[] };
    type: "channel" | "private";
  };

  type MessagesTableRow = {
    id: string;
    message: string;
    attachment: string;
    channel: ChannelTableRow;
    from: FromTableRow;
    createdAt: Date;
  };

  type MemberDefaultViewViewRow = {
    read: {
      id: string;
      email: string;
      role: { id: string; displayField: string };
      password: string;
      messages1: { nodes: Messages1TableRow[] };
      channels: { nodes: ChannelsTableRow[] };
    };
    write: {
      email: string;
      password: string;
      messages1: string[];
      channels: string[];
    };
    params: {};
    actions: {};
  };

  type ChannelDefaultViewViewRow = {
    read: {
      id: string;
      name: string;
      messages: { nodes: MessagesTableRow[] };
      member1: { nodes: Member1TableRow[] };
      type: "channel" | "private";
    };
    write: {
      name: string;
      messages: string[];
      member1: string[];
      type: "channel" | "private";
    };
    params: {};
    actions: {};
  };

  type MessagesDefaultViewViewRow = {
    read: {
      id: string;
      message: string;
      attachment: string;
      channel: ChannelTableRow;
      from: FromTableRow;
      createdAt: Date;
    };
    write: {
      message: string;
      attachment: string;
      channel: string[];
      from: string[];
      createdAt: Date;
    };
    params: {};
    actions: {};
  };

  type ChannelMessagesViewRow = {
    read: {
      id: string;
      message: string;
      attachment: string;
      channel: ChannelTableRow;
      from: FromTableRow;
      createdAt: Date;
    };
    write: {
      message: string;
      attachment: string;
      channel: string[];
      from: string[];
      createdAt: Date;
    };
    params: {
      channelID: string;
      "$by.createdAt"?: "desc";
    };
    actions: {};
  };

  type CurrentMemberViewRow = {
    read: {
      id: string;
      email: string;
      role: { id: string; displayField: string };
      password: string;
      messages1: { nodes: Messages1TableRow[] };
      channels: { nodes: ChannelsTableRow[] };
    };
    write: {
      email: string;
      password: string;
      messages1: string[];
      channels: string[];
    };
    params: {};
    actions: {};
  };

  interface ProjectSchema extends QoreSchema {
    memberDefaultView: MemberDefaultViewViewRow;
    channelDefaultView: ChannelDefaultViewViewRow;
    messagesDefaultView: MessagesDefaultViewViewRow;
    channelMessages: ChannelMessagesViewRow;
    currentMember: CurrentMemberViewRow;
  }
}
